
services:
  kaithem:
    extends:
      file: ./compose-groups.yml
      service: groups
    restart: unless-stopped
    image: cooperskeep/kaithem:0.97.0
    privileged: true

    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99


    user: "${KAITHEM_UID:?error}:${KAITHEM_GROUP:?error}"
    environment:
      DISPLAY: ${DISPLAY:-:0}
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY:-wayland-0}
      XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
      PIPEWIRE_REMOTE: pipewire-0
      USER: ${KAITHEM_USER:?error}
      LOGNAME: ${KAITHEM_USER:?error}
      DBUS_SESSION_BUS_ADDRESS: ${DBUS_SESSION_BUS_ADDRESS}
      KAITHEM_AUDIO_API: jack
      XDG_SESSION_TYPE: ${XDG_SESSION_TYPE}
      XAUTHORITY: ${XAUTHORITY}
      PIPEWIRE_LATENCY: "128/48000"
      PIPEWIRE_QUANTUM: "128/48000"

    volumes:
      # Seems to be needed for getpass.getuser()
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /usr/lib/locale:/usr/lib/locale:ro
      - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}
      - /var/run/dbus:/var/run/dbus
      - /dev:/dev
      - /tmp:/tmp
      - /sys/class:/sys/class

      # Use the host certificate bundle so we don't have to keep
      # updating the bundle
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro

      - $HOME/kaithem-docker-home:/app-home

    network_mode: host
    pid: host


  kiosk:
    # Started with xdg desktop after UI loads
    restart: "no"
    image: cooperskeep/kaithem-kiosk:0.97.0
    extends:
      file: ./compose-groups.yml
      service: groups
    pid: host

    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99

    security_opt:
    - apparmor:unconfined

    # For the GPU
    privileged: true

    user: "${KAITHEM_UID:?error}:${KAITHEM_GROUP:?error}"
    environment:
      DISPLAY: ${DISPLAY:-:0}
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY:-wayland-0}
      XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
      PIPEWIRE_REMOTE: pipewire-0
      USER: ${KAITHEM_USER:?error}
      HOME: /home/${KAITHEM_USER:?error}
      LOGNAME: ${KAITHEM_USER:?error}
      DBUS_SESSION_BUS_ADDRESS: ${DBUS_SESSION_BUS_ADDRESS}
      KAITHEM_AUDIO_API: jack
      XDG_SESSION_TYPE: ${XDG_SESSION_TYPE}
      XAUTHORITY: ${XAUTHORITY}
      PIPEWIRE_LATENCY: "128/48000"
      PIPEWIRE_QUANTUM: "128/48000"
      KIOSK_URL: ${KIOSK_URL:-http://localhost:8002}

    volumes:
      - /var/run/dbus:/var/run/dbus
      - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}
      - /dev:/dev
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /usr/lib/locale:/usr/lib/locale:ro


    network_mode: host


  matter:    
    image: ghcr.io/matter-js/matterjs-server:1.4.0
    volumes:
      - $HOME/kaithem-docker-home/matter:/app-home
      - /run/dbus:/run/dbus:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    
    environment:
      NOBLE_BINDINGS: dbus
      PRODUCTION_MODE: "true"
      ENABLE_TIME_SYNC: "true"
      ENABLE_TEST_NET_DCL: "true"

    network_mode: host
    security_opt:
      - apparmor:unconfined
    user: "${KAITHEM_UID}:${KAITHEM_GROUP}"
    restart: unless-stopped

    # Bypass verifier to allow self-signed certs
    command: >
      --listen-address 127.0.0.1    
